services:
  postgres:
    image: postgres:16.3
    container_name: email-manager-system-db
    environment:
      - POSTGRES_DB=email_manager_system
      - POSTGRES_USER=user_email_manager_system
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5532:5432"
