services:
  email-management-system-db:
    image: postgres:16.3
    container_name: email-management-system-db
    restart: always
    environment:
      - POSTGRES_DB=email_management_system
      - POSTGRES_USER=user_email_management_system
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5532:5432"
    volumes:
      - email-management-system-db-volume:/var/lib/postgresql/data
volumes:
  email-management-system-db-volume:
    name: email-management-system-db-volume
    external: true
